// Mealz v0.10: consolidated client architecture.
const DEV=new URLSearchParams(location.search).get('dev')==='true';
const DAY_ORDER=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const PROFILE_EQUIPMENT=['Oven','Stovetop','Broiler','Microwave','Toaster','Toaster Oven','Air Fryer','Pressure Cooker / Instant Pot','Slow Cooker','Griddle','Grill','Cast-Iron Skillet','Wok','Food Processor','Blender','Stand Mixer','Rice Cooker','Sous Vide','Dutch Oven'];
const DIET_GROUPS={
  'Dietary style':['Vegetarian','Vegan','Pescatarian','Mediterranean','Plant-Forward'],
  'Nutrition goals':['Keto','Low Carb','High Protein','Whole30','Low Sodium','Low Added Sugar'],
  'Dietary needs':['Gluten-Free','Dairy-Free','Nut-Free'],
  'General':['No Dietary Restrictions']
};
const GROCERY_STAPLES=new Set(['salt','table salt','kosher salt','sea salt','pepper','black pepper','ground black pepper']);
const DEFAULT_STATE={size:5,adults:3,children:2,eq:[],dietTags:[],meals:[],ideas:[],selectedIdeas:[],checked:{},planId:null,syncError:null,error:null,days:[],useUp:'',notes:''};
const TEST_WEEK=[
{id:'test-turkey-bowls',day:'Monday',title:'Ginger-Sesame Turkey Bowls',emoji:'🥢',description:'Savory turkey, crisp vegetables, edamame, and rice.',servings:5,total_minutes:25,difficulty:'Easy',tags:['Test meal','Kid friendly'],kid_note:'Serve sauce on the side.',ingredients:[{name:'ground turkey',quantity:1.5,unit:'lb',category:'Meat & Seafood'},{name:'shredded cabbage',quantity:1,unit:'bag',category:'Produce'},{name:'edamame',quantity:1,unit:'bag',category:'Frozen'},{name:'jasmine rice',quantity:2,unit:'packs',category:'Frozen'}],steps:['Cook or heat the rice.','Brown the turkey.','Add vegetables and sauce.','Serve over rice.']},
{id:'test-moroccan-chicken',day:'Thursday',title:'Moroccan Chicken & Couscous',emoji:'🍋',description:'Spiced chicken, roasted vegetables, couscous, and lemon yogurt.',servings:5,total_minutes:35,difficulty:'Easy',tags:['Test meal'],ingredients:[{name:'chicken thighs',quantity:1.75,unit:'lb',category:'Meat & Seafood'},{name:'zucchini',quantity:2,unit:'whole',category:'Produce'},{name:'Moroccan couscous',quantity:1,unit:'box',category:'Pantry'}],steps:['Roast chicken and vegetables.','Prepare couscous.','Serve together.']},
{id:'test-tacos',day:'Friday',title:'Sweet Potato Black Bean Tacos',emoji:'🌮',description:'Crispy sweet potatoes, black beans, avocado-lime slaw, and cheese.',servings:5,total_minutes:30,difficulty:'Easy',tags:['Vegetarian','Test meal'],ingredients:[{name:'sweet potatoes',quantity:2,unit:'whole',category:'Produce'},{name:'black beans',quantity:2,unit:'cans',category:'Pantry'},{name:'tortillas',quantity:12,unit:'small',category:'Bakery'}],steps:['Roast sweet potatoes.','Warm black beans.','Assemble tacos.']}
];
const GROCERY_TEST=[{name:'apples',quantity:4,unit:'whole',category:'Produce'},{name:'bananas',quantity:6,unit:'whole',category:'Produce'},{name:'broccoli',quantity:2,unit:'heads',category:'Produce'},{name:'carrots',quantity:1,unit:'bag',category:'Produce'},{name:'lemons',quantity:3,unit:'whole',category:'Produce'},{name:'garlic',quantity:1,unit:'head',category:'Produce'},{name:'chicken breasts',quantity:2,unit:'lb',category:'Meat & Seafood'},{name:'Greek yogurt',quantity:1,unit:'tub',category:'Dairy & Eggs'},{name:'eggs',quantity:1,unit:'dozen',category:'Dairy & Eggs'},{name:'tortillas',quantity:1,unit:'pack',category:'Bakery'},{name:'black beans',quantity:2,unit:'cans',category:'Pantry'},{name:'rice',quantity:1,unit:'bag',category:'Pantry'},{name:'olive oil',quantity:1,unit:'bottle',category:'Pantry'},{name:'frozen peas',quantity:1,unit:'bag',category:'Frozen'}];

let storageKey=null;
let s=structuredClone(DEFAULT_STATE);
let weeklyDraft={days:[],useUp:'',notes:''};
let readyIdeas=null;

function save(){if(storageKey&&globalThis.MealzAuth?.session)localStorage.setItem(storageKey,JSON.stringify(s))}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(i){return `${i.quantity??''} ${i.unit||''} ${i.name}`.replace(/\s+/g,' ').trim()}
function sortDays(days){return (days||[]).slice().sort((a,b)=>DAY_ORDER.indexOf(a)-DAY_ORDER.indexOf(b))}
function sortMealsByDay(meals){return (meals||[]).slice().sort((a,b)=>DAY_ORDER.indexOf(a.day)-DAY_ORDER.indexOf(b.day))}
function householdTotal(){return Math.max(1,(Number(s.adults)||0)+(Number(s.children)||0))}
function ideaCountForDays(n){return n>=5?Math.min(9,n+2):6}
function groceryKey(i){return `${i.category||'Other'}::${String(i.name||'').toLowerCase()}::${i.unit||''}`}
function planningWeekStart(){const d=new Date(),day=d.getDay();let diff=1-day;if(day===0)diff=1;if(day===5)diff=3;if(day===6)diff=2;d.setDate(d.getDate()+diff);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function friendlyClientError(message){const m=String(message||'');if(/gateway timeout|504|failed to fetch|networkerror/i.test(m))return 'A connection timed out. Your selections are still here, so you can try again safely.';if(/string did not match the expected pattern/i.test(m))return 'The recipe request hit a temporary browser connection error. Please try again.';if(/unexpected token|json/i.test(m))return 'Mealz received an incomplete server response. Please try again.';return m||'Something interrupted the request. Please try again.'}
function profilePayload(){return {householdSize:householdTotal(),adults:s.adults,children:s.children,dietTags:(s.dietTags||[]).filter(x=>x!=='No Dietary Restrictions'),equipment:s.eq||[]}}
function captureWeeklyDraft(){const u=document.querySelector('#useUp'),n=document.querySelector('#notes');if(u)weeklyDraft.useUp=u.value;if(n)weeklyDraft.notes=n.value}
function hasWeeklyOverrides(){return !!String(weeklyDraft.useUp||'').trim()||!!String(weeklyDraft.notes||'').trim()}
function preparedIdeasAvailable(count){return Array.isArray(readyIdeas?.ideas)&&readyIdeas.ideas.length>=count}
function canUsePreparedIdeas(count){return preparedIdeasAvailable(count)&&!hasWeeklyOverrides()}
function cloudNote(){if(DEV)return '<p class=small>Developer test mode is active. Test data stays on this device only.</p>';if(s.syncError)return `<div class="status">☁ <b>Cloud sync delayed.</b><br><span class="small">${esc(friendlyClientError(s.syncError))} Your plan remains saved on this device.</span></div>`;if(s.planId)return '<p class=small>☁ Saved to Mealz cloud</p>';return ''}
function view(v){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='meals')meals();else if(v==='groceries')groceries();else plan()}

async function apiJson(url,options){const r=await fetch(url,options);const text=await r.text();let d={};if(text){try{d=JSON.parse(text)}catch{d={error:text}}}if(!r.ok)throw new Error(d.error||`Request failed (${r.status}).`);return d}
async function loadProfile(){if(DEV)return;try{const d=await apiJson('/api/profile');if(!d.profile)return;const p=d.profile;s.adults=Math.max(0,Number(p.adults||0));s.children=Math.max(0,Number(p.children||0));s.dietTags=Array.isArray(p.dietTags)?p.dietTags:[];s.eq=Array.isArray(p.equipment)?p.equipment.filter(x=>PROFILE_EQUIPMENT.includes(x)):[];s.size=householdTotal();save()}catch(e){throw new Error('Could not load your Profile. Please try again.')}}
async function saveProfileCloud(){if(DEV)return;await apiJson('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profilePayload())});readyIdeas=null}
async function loadActivePlan(){if(DEV)return;try{const d=await apiJson('/api/plan');if(!d.plan)return;s.meals=sortMealsByDay(d.meals||[]);s.planId=d.plan.id;s.days=d.plan.cooking_days||[];s.useUp=d.plan.use_up||'';s.notes=d.plan.notes||'';s.checked={};for(const i of d.groceryItems||[])s.checked[groceryKey(i)]=!!i.checked;s.syncError=null;save()}catch(e){s.syncError=e.message;save()}}
async function loadReadyIdeas(){if(DEV)return;try{const d=await apiJson(`/api/pregenerated-ideas?week_start=${encodeURIComponent(planningWeekStart())}`);readyIdeas=Array.isArray(d.ideas)&&d.ideas.length?d:null}catch(e){console.warn('Prepared ideas unavailable',e);readyIdeas=null}}
async function syncPlan(){try{const d=await apiJson('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({weekStart:planningWeekStart(),householdSize:householdTotal(),days:sortDays(s.days),equipment:s.eq||[],useUp:s.useUp,notes:s.notes,meals:sortMealsByDay(s.meals)})});s.planId=d.planId;s.syncError=null;save()}catch(e){throw new Error(friendlyClientError(e.message))}}

function devTools(){return DEV?`<div class="section card"><h2>Developer Tools</h2><p class=small>Visible only when Mealz is opened with <b>?dev=true</b>.</p><button id=loadWeek class=secondary style="width:100%;margin-bottom:8px">Load Sample Week</button><button id=loadGroceries class=secondary style="width:100%;margin-bottom:8px">Load Grocery Test List</button><button id=resetData class=secondary style="width:100%">Reset App Data</button></div>`:''}
function wireDevTools(){if(!DEV)return;document.querySelector('#loadWeek').onclick=()=>{s.meals=structuredClone(TEST_WEEK);s.checked={};s.planId=null;save();view('meals')};document.querySelector('#loadGroceries').onclick=()=>{s.meals=[{id:'grocery-ux-test',day:'Test',title:'Grocery UX Test',emoji:'🛒',description:'Temporary test data for grocery-list interactions.',servings:householdTotal(),total_minutes:0,difficulty:'Test',tags:['Developer'],ingredients:structuredClone(GROCERY_TEST),steps:[]}];s.checked={};s.planId=null;save();view('groceries')};document.querySelector('#resetData').onclick=()=>{localStorage.removeItem('mealz');s={...DEFAULT_STATE};weeklyDraft={days:[],useUp:'',notes:''};plan()}}

function plan(){
  const count=ideaCountForDays(weeklyDraft.days.length),prepared=canUsePreparedIdeas(count);
  app.innerHTML=`<h1>Plan This Week</h1><p class=subtle>Choose what this week looks like. Weekly details start fresh each time you open Mealz.</p>${s.error?`<div class="status error">${esc(s.error)}</div>`:''}${cloudNote()}${prepared?`<div class="status ready-ideas">🍲 <b>${count} ideas are ready.</b><br><span class="small">Mealz prepared options ahead of time. Adjust this week first if you need to.</span></div>`:''}<div class=section><label class=label>Which days are you cooking?</label><div class=day-grid>${DAY_ORDER.map(d=>`<button class="day-btn ${weeklyDraft.days.includes(d)?'selected':''}" data-d="${d}">${d.slice(0,3)}</button>`).join('')}</div></div><div class=section><label class=label>Any ingredients to use up?</label><input id=useUp value="${esc(weeklyDraft.useUp)}" placeholder="Optional"></div><div class=section><label class=label>Anything else?</label><textarea id=notes placeholder="Optional">${esc(weeklyDraft.notes)}</textarea></div><button id=go class=primary>${prepared?`See ${count} Ready Ideas ✨`:`Find ${count} Meal Ideas ✨`}</button><div class="section card household-summary"><div><h2>Household</h2><p>${s.adults} adult${s.adults===1?'':'s'} · ${s.children} child${s.children===1?'':'ren'} · ${(s.dietTags||[]).length?s.dietTags.join(' · '):'No dietary style selected'}</p></div><button class=secondary id=openProfile>Edit</button></div>${devTools()}`;
  document.querySelectorAll('.day-btn').forEach(b=>b.onclick=()=>{captureWeeklyDraft();const d=b.dataset.d;weeklyDraft.days=weeklyDraft.days.includes(d)?weeklyDraft.days.filter(x=>x!==d):sortDays([...weeklyDraft.days,d]);s.error=null;plan()});
  document.querySelector('#go').onclick=generateIdeas;
  document.querySelector('#openProfile').onclick=profile;
  wireDevTools();
}

function toggleDietTag(tag){if(tag==='No Dietary Restrictions')s.dietTags=s.dietTags.includes(tag)?[]:['No Dietary Restrictions'];else{s.dietTags=(s.dietTags||[]).filter(x=>x!=='No Dietary Restrictions');s.dietTags=s.dietTags.includes(tag)?s.dietTags.filter(x=>x!==tag):[...s.dietTags,tag]}s.size=householdTotal();save();profile()}
function profile(){
  app.innerHTML=`<h1>Household</h1><p class=subtle>Set the preferences Mealz should remember from week to week.</p><div class="section card"><h2>Who are we feeding?</h2><div class=profile-counter><div><b>Adults</b><p class=small>Full-size servings</p></div><div class=counter><button id=adultMinus>−</button><div class=counter-value>${s.adults}</div><button id=adultPlus>+</button></div></div><div class=profile-counter><div><b>Children</b><p class=small>Mealz will keep meals kid-adaptable</p></div><div class=counter><button id=childMinus>−</button><div class=counter-value>${s.children}</div><button id=childPlus>+</button></div></div><p class=small>${householdTotal()} people total. Recipe quantities currently use the total headcount.</p></div>${Object.entries(DIET_GROUPS).map(([group,tags])=>`<div class="section card"><h2>${esc(group)}</h2><div class=preference-grid>${tags.map(t=>`<button class="preference-btn ${s.dietTags.includes(t)?'selected':''}" data-tag="${t}">${t}</button>`).join('')}</div></div>`).join('')}<div class="section card"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px"><div><h2 style="margin:0">Kitchen equipment</h2><p class=small style="margin:6px 0 0">Select special equipment Mealz may design recipes around. Clear means no special equipment preference.</p></div><button class=secondary id=clearEquipment type=button>Clear</button></div><div class=equipment-grid style="margin-top:12px">${PROFILE_EQUIPMENT.map(e=>`<button class="equipment-btn ${s.eq.includes(e)?'selected':''}" data-e="${e}">${e}</button>`).join('')}</div></div><button class=primary id=profileDone>Save Household</button>`;
  document.querySelector('#adultMinus').onclick=()=>{s.adults=Math.max(0,s.adults-1);s.size=householdTotal();save();profile()};
  document.querySelector('#adultPlus').onclick=()=>{s.adults=Math.min(20,s.adults+1);s.size=householdTotal();save();profile()};
  document.querySelector('#childMinus').onclick=()=>{s.children=Math.max(0,s.children-1);s.size=householdTotal();save();profile()};
  document.querySelector('#childPlus').onclick=()=>{s.children=Math.min(20,s.children+1);s.size=householdTotal();save();profile()};
  document.querySelectorAll('.preference-btn').forEach(b=>b.onclick=()=>toggleDietTag(b.dataset.tag));
  document.querySelectorAll('.equipment-btn').forEach(b=>b.onclick=()=>{const e=b.dataset.e;s.eq=s.eq.includes(e)?s.eq.filter(x=>x!==e):[...s.eq,e];save();profile()});
  document.querySelector('#clearEquipment').onclick=()=>{s.eq=[];save();profile()};
  document.querySelector('#profileDone').onclick=async()=>{
    const btn=document.querySelector('#profileDone');btn.disabled=true;btn.textContent='Saving…';
    document.querySelector('#profileSaveError')?.remove();
    try{await saveProfileCloud();s.syncError=null;save();view('plan')}
    catch(e){
      s.syncError=e.message;btn.disabled=false;btn.textContent='Save Profile';
      const message=document.createElement('p');message.id='profileSaveError';message.setAttribute('role','alert');message.textContent=e.message;btn.before(message);
    }
  };
}

async function generateIdeas(){
  captureWeeklyDraft();s.error=null;s.syncError=null;weeklyDraft.days=sortDays(weeklyDraft.days);s.size=householdTotal();save();
  if(!weeklyDraft.days.length){s.error='Choose at least one cooking day.';return plan()}
  const count=ideaCountForDays(weeklyDraft.days.length);
  if(canUsePreparedIdeas(count)){s.ideas=readyIdeas.ideas.slice(0,count);s.selectedIdeas=[];save();return ideaPicker()}
  const btn=document.querySelector('#go');btn.disabled=true;btn.textContent=`Finding ${count} good options…`;
  try{const d=await apiJson('/api/generate-ideas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({days:weeklyDraft.days,ideaCount:count,...profilePayload(),useUp:weeklyDraft.useUp,notes:weeklyDraft.notes})});s.ideas=(d.ideas||[]).slice(0,count);s.selectedIdeas=[];save();ideaPicker()}catch(e){s.error=friendlyClientError(e.message);save();plan()}
}
function selectionNumber(id){const i=s.selectedIdeas.indexOf(id);return i<0?'':String(i+1)}
function toggleIdea(id){const i=s.selectedIdeas.indexOf(id),limit=weeklyDraft.days.length;if(i>=0)s.selectedIdeas.splice(i,1);else if(s.selectedIdeas.length<limit)s.selectedIdeas.push(id);else return;save();ideaPicker()}
function ideaPicker(){weeklyDraft.days=sortDays(weeklyDraft.days);const needed=weeklyDraft.days.length,chosen=s.selectedIdeas.length,count=ideaCountForDays(needed);app.innerHTML=`<button class=secondary id=editPlan>← Edit Plan</button><h1>Pick ${needed} Dinner${needed===1?'':'s'}</h1><p class=subtle>Choose your favorites from ${count} ideas. Recipes and groceries are generated only after you decide.</p><div class="selection-status ${chosen===needed?'ready':''}"><b>${chosen} of ${needed} selected</b>${chosen?`<div class=small>${s.selectedIdeas.map((id,i)=>`${i+1} → ${esc(weeklyDraft.days[i]||'')}`).join(' · ')}</div>`:''}</div><div class=idea-grid>${(s.ideas||[]).map(x=>{const n=selectionNumber(x.id);return `<button class="idea-card ${n?'selected-idea':''}" data-id="${esc(x.id)}"><div class=idea-top><span class=idea-emoji>${esc(x.emoji||'🍽️')}</span>${n?`<span class=pick-number>${n}</span>`:''}</div><div class=idea-title>${esc(x.title)}</div><p>${esc(x.description)}</p><div><span class=pill>${x.total_minutes||30} min</span>${x.protein?`<span class=pill>${esc(x.protein)}</span>`:''}${(x.tags||[]).slice(0,2).map(t=>`<span class=pill>${esc(t)}</span>`).join('')}</div></button>`}).join('')}</div><div class=picker-actions><button class=secondary id=refreshIdeas>Give Me ${count} Different Ideas</button><button class=primary id=buildWeek ${chosen===needed?'':'disabled'}>${chosen===needed?'Build My Week →':`Pick ${needed-chosen} More`}</button></div>`;document.querySelector('#editPlan').onclick=plan;document.querySelectorAll('.idea-card').forEach(b=>b.onclick=()=>toggleIdea(b.dataset.id));document.querySelector('#refreshIdeas').onclick=refreshMealIdeas;document.querySelector('#buildWeek').onclick=()=>{if(s.selectedIdeas.length===needed)buildSelectedWeek()}}
async function refreshMealIdeas(){const count=ideaCountForDays(weeklyDraft.days.length);app.innerHTML=`<h1>Fresh ideas coming up…</h1><div class="status swap-loading">✨ Shuffling ${count} dinner ideas…</div>`;try{const d=await apiJson('/api/generate-ideas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({days:weeklyDraft.days,ideaCount:count,...profilePayload(),useUp:weeklyDraft.useUp,notes:`${weeklyDraft.notes||''}\nGive a substantially different set from these previous ideas: ${(s.ideas||[]).map(x=>x.title).join(', ')}`})});s.ideas=(d.ideas||[]).slice(0,count);s.selectedIdeas=[];save();ideaPicker()}catch(e){s.error=friendlyClientError(e.message);save();plan()}}
async function buildSelectedWeek(){const picked=s.selectedIdeas.map(id=>s.ideas.find(x=>x.id===id)).filter(Boolean);weeklyDraft.days=sortDays(weeklyDraft.days);if(picked.length!==weeklyDraft.days.length)return ideaPicker();s.days=weeklyDraft.days;s.useUp=weeklyDraft.useUp.trim();s.notes=weeklyDraft.notes.trim();s.size=householdTotal();save();app.innerHTML=`<h1>Building your week…</h1><p class=subtle>Now Mealz is creating recipes only for the dinners you picked.</p><div class="status swap-loading">🥕 Writing recipes and assembling groceries…</div>`;try{const d=await apiJson('/api/expand-meals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({days:s.days,selectedIdeas:picked,...profilePayload(),useUp:s.useUp,notes:s.notes})});s.meals=sortMealsByDay(d.meals||[]);s.checked={};s.planId=null;s.syncError=null;s.error=null;save();if(!DEV){try{await syncPlan()}catch(e){s.syncError=e.message;save()}}view('meals')}catch(e){app.innerHTML=`<button class=secondary id=backIdeas>← Back to Ideas</button><h1>That batch didn’t come together</h1><div class="status error">${esc(friendlyClientError(e.message))}</div><button class=primary id=retryBuild>Try Building Again</button>`;document.querySelector('#backIdeas').onclick=ideaPicker;document.querySelector('#retryBuild').onclick=buildSelectedWeek}}

function isMakeAgain(m){return Array.isArray(m.tags)&&m.tags.includes('Make again')}
function mealCard(m){const liked=isMakeAgain(m);return `<div class="card meal-card" data-id="${esc(m.id)}"><div class=meal-day>${esc(m.day).toUpperCase()}</div><div class=meal-title>${esc(m.emoji||'🍽️')} ${esc(m.title)}</div><p>${esc(m.description)}</p><div><span class=pill>${m.total_minutes||30} min</span>${(m.tags||[]).filter(t=>t!=='Make again').map(t=>`<span class=pill>${esc(t)}</span>`).join('')}</div><div class=meal-actions><button class="secondary view-recipe" data-id="${esc(m.id)}">View Recipe</button><button class="secondary swap-meal" data-id="${esc(m.id)}">Swap Meal</button></div><button class="make-again ${liked?'liked':''}" data-id="${esc(m.id)}" aria-pressed="${liked?'true':'false'}">${liked?'♥':'♡'} Make Again</button></div>`}
function meals(){s.meals=sortMealsByDay(s.meals);if(!s.meals.length){app.innerHTML='<h1>Your Meal Plan</h1><div class=status>No generated plan yet.</div>';return}app.innerHTML=`<h1>Your Meal Plan</h1><p class=subtle>${s.meals.length} meals · ${householdTotal()} people</p>${cloudNote()}<p class="small learning-note">♡ Tap <b>Make Again</b> on a keeper. Mealz will use those choices to shape future ideas.</p>${s.meals.map(mealCard).join('')}`;document.querySelectorAll('.view-recipe').forEach(b=>b.onclick=e=>{e.stopPropagation();recipe(b.dataset.id)});document.querySelectorAll('.swap-meal').forEach(b=>b.onclick=e=>{e.stopPropagation();swapMeal(b.dataset.id)});document.querySelectorAll('.make-again').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleMakeAgain(b.dataset.id)})}
function recipe(id){const m=s.meals.find(x=>x.id===id);if(!m)return;app.innerHTML=`<button class=secondary id=back>← Back</button><h1>${esc(m.emoji||'🍽️')} ${esc(m.title)}</h1><p>${esc(m.description)}</p><span class=pill>${m.servings||householdTotal()} servings</span><span class=pill>${m.total_minutes||30} min</span><div class=section><h2>Ingredients</h2><ul class=recipe-list>${(m.ingredients||[]).map(i=>`<li><input type=checkbox><span>${esc(fmt(i))}</span></li>`).join('')}</ul></div><div class=section><h2>Instructions</h2><ol>${(m.steps||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div>${m.kid_note?`<div class=status><b>Kid option:</b> ${esc(m.kid_note)}</div>`:''}`;document.querySelector('#back').onclick=meals}
async function toggleMakeAgain(id){const m=s.meals.find(x=>x.id===id);if(!m)return;const next=!isMakeAgain(m);m.tags=Array.isArray(m.tags)?m.tags.filter(t=>t!=='Make again'):[];if(next)m.tags.push('Make again');save();meals();if(DEV||!s.planId)return;try{await apiJson('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({planId:s.planId,mealId:id,makeAgain:next})})}catch(e){s.syncError=e.message;save();meals()}}
async function swapMeal(id){const original=s.meals.find(m=>m.id===id);if(!original)return;app.innerHTML=`<button class=secondary id=cancelSwap>← Back</button><h1>Swap ${esc(original.day)}</h1><p class=subtle>Finding two alternatives for ${esc(original.title)}…</p><div class="status swap-loading">✨ Stirring the idea pot…</div>`;document.querySelector('#cancelSwap').onclick=meals;try{const d=await apiJson('/api/swap-meal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({meal:original,otherMeals:s.meals.filter(m=>m.id!==id).map(m=>({title:m.title,day:m.day})),...profilePayload(),useUp:s.useUp,notes:s.notes})});showSwapChoices(original,d.alternatives||[])}catch(e){app.innerHTML=`<button class=secondary id=backSwapError>← Back</button><h1>Swap ${esc(original.day)}</h1><div class="status error">${esc(e.message)}</div><button class=primary id=retrySwap>Try Again</button>`;document.querySelector('#backSwapError').onclick=meals;document.querySelector('#retrySwap').onclick=()=>swapMeal(id)}}
function showSwapChoices(original,alts){app.innerHTML=`<button class=secondary id=cancelChoices>← Keep Current Meal</button><h1>Pick a replacement</h1><p class=subtle>Here are two different directions for ${esc(original.day)}.</p>${alts.map((m,i)=>`<div class="card swap-choice"><div class=meal-day>OPTION ${i+1}</div><div class=meal-title>${esc(m.emoji||'🍽️')} ${esc(m.title)}</div><p>${esc(m.description)}</p><span class=pill>${m.total_minutes||30} min</span>${(m.tags||[]).map(t=>`<span class=pill>${esc(t)}</span>`).join('')}<button class="primary choose-swap" data-i="${i}">Choose This Meal</button></div>`).join('')}`;document.querySelector('#cancelChoices').onclick=meals;document.querySelectorAll('.choose-swap').forEach(b=>b.onclick=()=>applySwap(original.id,alts[Number(b.dataset.i)]))}
async function applySwap(originalId,replacement){const old=s.meals.find(m=>m.id===originalId);if(!old||!replacement)return;replacement={...replacement,day:old.day};s.meals=s.meals.map(m=>m.id===originalId?replacement:m);s.syncError=null;save();app.innerHTML='<h1>Updating your week…</h1><div class=status>🛒 Rebuilding groceries and saving the swap…</div>';if(!DEV){try{await syncPlan()}catch(e){s.syncError=e.message;save()}}meals()}

function groceryData(){const map=new Map();for(const m of s.meals||[])for(const i of m.ingredients||[]){if(i.optional)continue;if(GROCERY_STAPLES.has(String(i.name||'').trim().toLowerCase()))continue;const category=i.category||'Other',key=groceryKey({...i,category}),e=map.get(key);if(e&&typeof i.quantity==='number'&&typeof e.quantity==='number')e.quantity+=i.quantity;else if(!e)map.set(key,{key,...i,category})}return [...map.values()]}
async function syncGrocery(item,checked){if(DEV||!s.planId)return;try{await apiJson('/api/plan',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({planId:s.planId,name:item.name,unit:item.unit||null,category:item.category||'Other',checked})});s.syncError=null;save()}catch(e){s.syncError=e.message;save()}}
function groceries(animateKey){const before={};if(animateKey&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches)document.querySelectorAll('.grocery-item[data-key]').forEach(el=>before[el.dataset.key]=el.getBoundingClientRect().top);if(!s.meals.length){app.innerHTML='<h1>Grocery List</h1><div class=status>Generate a plan first.</div>';return}const a=groceryData(),cats=[...new Set(a.map(i=>i.category))];app.innerHTML=`<h1>Grocery List</h1><p class=subtle>Trader Joe's first · Wegmans backup</p>${cloudNote()}<p class=small>Checked items move to the bottom of their section.</p>${cats.map(c=>{const z=a.filter(i=>i.category===c).sort((x,y)=>(s.checked[x.key]?1:0)-(s.checked[y.key]?1:0)||x.name.localeCompare(y.name));return `<section class=category><h3>${esc(c)}</h3>${z.map(i=>`<label class="grocery-item ${s.checked[i.key]?'checked':''}" data-key="${encodeURIComponent(i.key)}"><input type=checkbox data-k="${encodeURIComponent(i.key)}" ${s.checked[i.key]?'checked':''}><span>${esc(fmt(i))}</span></label>`).join('')}</section>`}).join('')}`;if(animateKey&&Object.keys(before).length)requestAnimationFrame(()=>{document.querySelectorAll('.grocery-item[data-key]').forEach(el=>{const old=before[el.dataset.key];if(old==null)return;const delta=old-el.getBoundingClientRect().top;if(Math.abs(delta)>1)el.animate([{transform:`translateY(${delta}px)`},{transform:'translateY(0)'}],{duration:340,easing:'cubic-bezier(.2,.8,.2,1)'})});const moved=document.querySelector(`.grocery-item[data-key="${CSS.escape(encodeURIComponent(animateKey))}"]`);if(moved)moved.animate([{opacity:.55},{opacity:1}],{duration:340,easing:'ease-out'})});document.querySelectorAll('.grocery-item input').forEach(b=>b.onchange=()=>{const k=decodeURIComponent(b.dataset.k),item=a.find(i=>i.key===k);s.checked[k]=b.checked;save();groceries(k);if(item)syncGrocery(item,b.checked)})}

async function boot(){
  document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>view(b.dataset.view));
  if(!Array.isArray(s.eq))s.eq=[];if(!Array.isArray(s.dietTags))s.dietTags=[];if(!Number.isFinite(Number(s.adults)))s.adults=3;if(!Number.isFinite(Number(s.children)))s.children=Math.max(0,(Number(s.size)||5)-s.adults);s.size=householdTotal();
  await loadProfile();
  await loadActivePlan();
  await loadReadyIdeas();
  save();
  await plan();
}
// account-client.js starts boot only after auth and household resolution.
