// Mealz v0.7.1: resilience patch for transient API/cloud failures.
function friendlyClientError(message){const m=String(message||'');if(/gateway timeout|504|failed to fetch|networkerror/i.test(m))return 'A connection timed out. Your selections are still here, so you can try again safely.';if(/string did not match the expected pattern/i.test(m))return 'The recipe request hit a temporary browser connection error. Please try again.';if(/unexpected token|json/i.test(m))return 'Mealz received an incomplete server response. Please try again.';return m||'Something interrupted the request. Please try again.'}
function sortMealsByDay(meals){return (meals||[]).slice().sort((a,b)=>DAY_ORDER.indexOf(a.day)-DAY_ORDER.indexOf(b.day))}

cloudNote=function(){if(DEV)return '<p class=small>Developer test mode is active. Test data stays on this device only.</p>';if(s.syncError)return `<div class="status">☁ <b>Cloud sync delayed.</b><br><span class="small">${esc(friendlyClientError(s.syncError))} Your plan remains saved on this device.</span></div>`;if(s.planId)return '<p class=small>☁ Saved to Mealz cloud</p>';return ''}

syncPlan=async function(){let r;try{r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({weekStart:planningWeekStart(),householdSize:s.size,days:sortDays(s.days),equipment:s.eq,useUp:s.useUp,notes:s.notes,meals:sortMealsByDay(s.meals)})})}catch(e){throw new Error(friendlyClientError(e.message))}const text=await r.text();let d={};if(text){try{d=JSON.parse(text)}catch{d={error:text}}}if(!r.ok){if([502,503,504].includes(r.status))throw new Error('Cloud sync is temporarily unavailable.');throw new Error(d.error||`Cloud sync failed (${r.status}).`)}s.planId=d.planId;s.syncError=null;save()}

async function expandRequest(payload){try{return await fetch('/api/expand-meals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})}catch(first){if(/string did not match the expected pattern|failed to fetch|networkerror/i.test(String(first?.message||''))){await new Promise(r=>setTimeout(r,400));return fetch('/api/expand-meals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})}throw first}}

buildSelectedWeek=async function(){const picked=s.selectedIdeas.map(id=>s.ideas.find(x=>x.id===id)).filter(Boolean);s.days=sortDays(s.days);if(picked.length!==s.days.length)return ideaPicker();app.innerHTML=`<h1>Building your week…</h1><p class=subtle>Now Mealz is creating recipes only for the dinners you picked.</p><div class="status swap-loading">🥕 Writing recipes and assembling groceries…</div>`;try{const payload={days:s.days,selectedIdeas:picked,householdSize:s.size,equipment:s.eq,useUp:s.useUp,notes:s.notes};const r=await expandRequest(payload);const text=await r.text();let d={};if(text){try{d=JSON.parse(text)}catch{throw new Error('Mealz received an incomplete server response.')}}if(!r.ok)throw new Error(d.error||`Recipe generation failed (${r.status}).`);s.meals=sortMealsByDay(d.meals||[]);s.checked={};s.planId=null;s.syncError=null;s.error=null;save();if(!DEV){try{await syncPlan()}catch(e){s.syncError=e.message;save()}}view('meals')}catch(e){app.innerHTML=`<button class=secondary id=backIdeas>← Back to Ideas</button><h1>That batch didn’t come together</h1><div class="status error">${esc(friendlyClientError(e.message))}</div><button class=primary id=retryBuild>Try Building Again</button>`;backIdeas.onclick=ideaPicker;retryBuild.onclick=buildSelectedWeek}}

const v071MealsView=meals;
meals=function(){if(Array.isArray(s.meals)){const sorted=sortMealsByDay(s.meals);if(sorted.some((m,i)=>m!==s.meals[i])){s.meals=sorted;save()}}return v071MealsView()}
